name: CI PR Test

on:
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/ci-pr-test.yaml
      - .github/workflows/e2e-*-xpu.yaml
      - docker/Dockerfile.xpu
      - guides/**/values_xpu.yaml
      - guides/pd-disaggregation/ms-pd/values_xpu.yaml
      - guides/pd-disaggregation/README.xpu.md
      - guides/pd-disaggregation/helmfile.yaml.gotmpl
      - guides/inference-scheduling/ms-inference-scheduling/values_xpu.yaml
      - guides/inference-scheduling/helmfile.yaml.gotmpl
  workflow_dispatch:
    inputs:
      pr_or_branch:
        description: 'Pull-request number or branch name to test'
        required: true
        default: 'main'
        type: string
      custom_image_tag:
        description: 'Custom XPU image tag to use (optional)'
        required: false
        default: ''
        type: string

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  # Call the build-image workflow to build any changed images
  build-images:
    uses: ./.github/workflows/build-image.yml
    secrets: inherit

  # Call the XPU Inference Scheduling test workflow
  test-xpu-inference-scheduling:
    needs: build-images
    if: ${{ !cancelled() }}
    uses: ./.github/workflows/e2e-inference-scheduling-xpu.yaml
    with:
      pr_or_branch: ${{ github.event.inputs.pr_or_branch || github.event.pull_request.number }}
      custom_image_tag: ${{ github.event.inputs.custom_image_tag || github.event.pull_request.number }}
    secrets: inherit

  # Call the XPU PD Disaggregation test workflow
  test-xpu-pd-disaggregation:
    needs: build-images
    if: ${{ !cancelled() }}
    uses: ./.github/workflows/e2e-pd-disaggregation-xpu.yaml
    with:
      pr_or_branch: ${{ github.event.inputs.pr_or_branch || github.event.pull_request.number }}
      custom_image_tag: ${{ github.event.inputs.custom_image_tag || github.event.pull_request.number }}
    secrets: inherit
